In [1]:
#Arrays

In [5]:
import numpy as np

In [6]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
a.shape

(2, 4)

In [8]:
a[1,3]

7

In [9]:
a[1,2] = 8
a

array([[0, 1, 2, 3],
       [4, 5, 8, 7]])

In [10]:
a[0]

array([0, 1, 2, 3])

In [11]:
a[1]

array([4, 5, 8, 7])

In [12]:
#Números aleatórios

In [13]:
import random

In [14]:
prob = random.random()
print(prob)

0.4987809809317617


In [15]:
number = random.randint(1,6)
print(number)

4


In [18]:
#criando um data frame com dados aleatórios
import numpy as np
import random

In [19]:
np.random.randint(1,6,(4,6))

array([[2, 5, 1, 5, 4, 1],
       [4, 4, 5, 1, 5, 3],
       [4, 3, 1, 1, 1, 4],
       [1, 2, 3, 5, 2, 4]])